In [1]:
!ls

brouillon.ipynb  data  Evaluation.py  main.py


In [14]:
import os
import json 
import numpy as np 
import random


In [3]:
def load_json_data(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data

def extract_pressure_matrices(json_data):
    pressure_matrices = []
    for entry in json_data['pressureData']:
        pressure_matrix = entry["pressureMatrix"]
        pressure_matrices.append({"pressureMatrix": pressure_matrix})
    return pressure_matrices

def extract_features_from_pressure_matrices(pressure_matrices):
    flattened_data = [np.array(item["pressureMatrix"]).flatten() for item in pressure_matrices]
    return np.concatenate(flattened_data, axis=0)

In [16]:
dic = {}
lab = {}
for i in range(6,9):
    folder_path = f'data/Subject_{i}/Posture_data'

    # Get all files in the folder
    files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
    labels = [int(f.split('.')[0][-1])for f in files]
    l = []

    for f in files:
        file_path = os.path.join(folder_path, f)
        # Check if the file is a JSON file
        if file_path.endswith('.json'):
            with open(file_path, 'r') as file:
                try:
                    data = json.load(file) 
                    pressure_matrices = extract_pressure_matrices(data)
                    features = extract_features_from_pressure_matrices(pressure_matrices)
                    l.append(features)
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON in file {file_path}: {e}")
        else:
            print(f"Skipping non-JSON file: {file_path}")
     
    num = list(range(7))
    random.shuffle(num)
    
    dic[i] = [l[j] for j in num]
    lab[i] = [labels[j] for j in num]


In [17]:
dic

{6: [array([193., 107., 293., ...,   4.,   3.,   2.]),
  array([4., 4., 4., ..., 3., 0., 0.]),
  array([ 86., 114., 127., ..., 192.,   5.,   2.]),
  array([14., 11., 20., ...,  3.,  0.,  0.]),
  array([ 33.,  97., 111., ..., 358.,  30.,  23.]),
  array([  7.,  26., 225., ...,   2.,   0.,   2.]),
  array([3., 3., 3., ..., 3., 2., 0.])],
 7: [array([ 10., 270., 379., ...,   2.,   0.,   0.]),
  array([131., 187., 160., ...,   3.,   2.,   0.]),
  array([278., 292., 326., ...,   0.,   0.,   0.]),
  array([4., 7., 8., ..., 2., 0., 0.]),
  array([ 13., 222., 304., ...,   9.,   4.,   0.]),
  array([388., 401., 411., ...,   0.,   0.,   0.]),
  array([ 8.,  8.,  8., ..., 43.,  8.,  2.])],
 8: [array([  0.,   2.,   4., ..., 234., 184., 185.]),
  array([  6.,  13., 124., ...,  11.,   8.,   5.]),
  array([  7.,  10.,  16., ..., 212., 147., 131.]),
  array([ 10.,  12., 177., ...,   8.,   6.,   7.]),
  array([  4.,   4.,  12., ..., 164.,  49.,  24.]),
  array([ 13.,   8., 100., ..., 184.,  48.,  24.]