In [1]:
!ls

brouillon.ipynb  data  Evaluation.py  main.py


In [14]:
import os
import json 
import numpy as np 
import random


In [3]:
def load_json_data(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data

def extract_pressure_matrices(json_data):
    pressure_matrices = []
    for entry in json_data['pressureData']:
        pressure_matrix = entry["pressureMatrix"]
        pressure_matrices.append({"pressureMatrix": pressure_matrix})
    return pressure_matrices

def extract_features_from_pressure_matrices(pressure_matrices):
    flattened_data = [np.array(item["pressureMatrix"]).flatten() for item in pressure_matrices]
    return np.concatenate(flattened_data, axis=0)

In [16]:
dic = {}
lab = {}
for i in range(6,9):
    folder_path = f'data/Subject_{i}/Posture_data'

    # Get all files in the folder
    files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
    labels = [int(f.split('.')[0][-1])for f in files]
    l = []

    for f in files:
        file_path = os.path.join(folder_path, f)
        # Check if the file is a JSON file
        if file_path.endswith('.json'):
            with open(file_path, 'r') as file:
                try:
                    data = json.load(file) 
                    pressure_matrices = extract_pressure_matrices(data)
                    features = extract_features_from_pressure_matrices(pressure_matrices)
                    l.append(features)
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON in file {file_path}: {e}")
        else:
            print(f"Skipping non-JSON file: {file_path}")
     
    num = list(range(7))
    random.shuffle(num)
    
    dic[i] = [l[j] for j in num]
    lab[i] = [labels[j] for j in num]


In [17]:
dic

{6: [array([193., 107., 293., ...,   4.,   3.,   2.]),
  array([4., 4., 4., ..., 3., 0., 0.]),
  array([ 86., 114., 127., ..., 192.,   5.,   2.]),
  array([14., 11., 20., ...,  3.,  0.,  0.]),
  array([ 33.,  97., 111., ..., 358.,  30.,  23.]),
  array([  7.,  26., 225., ...,   2.,   0.,   2.]),
  array([3., 3., 3., ..., 3., 2., 0.])],
 7: [array([ 10., 270., 379., ...,   2.,   0.,   0.]),
  array([131., 187., 160., ...,   3.,   2.,   0.]),
  array([278., 292., 326., ...,   0.,   0.,   0.]),
  array([4., 7., 8., ..., 2., 0., 0.]),
  array([ 13., 222., 304., ...,   9.,   4.,   0.]),
  array([388., 401., 411., ...,   0.,   0.,   0.]),
  array([ 8.,  8.,  8., ..., 43.,  8.,  2.])],
 8: [array([  0.,   2.,   4., ..., 234., 184., 185.]),
  array([  6.,  13., 124., ...,  11.,   8.,   5.]),
  array([  7.,  10.,  16., ..., 212., 147., 131.]),
  array([ 10.,  12., 177., ...,   8.,   6.,   7.]),
  array([  4.,   4.,  12., ..., 164.,  49.,  24.]),
  array([ 13.,   8., 100., ..., 184.,  48.,  24.]

In [21]:
import pickle
with open ('Results/features_dic.pkl','rb') as file:
    dic = pickle.load(file)

with open ('Results/labels_dic.pkl','rb') as file:
    lab = pickle.load(file)  
features=list(dic.values())

labels = list(lab.values())

In [22]:
alllabels = [labels[-1], labels[0],labels[1]]

ylabels1 = []

    # Convert each one-hot encoded array to labels and append them to the list
for array in alllabels:
    labels = np.argmax(array, axis=1)
    ylabels1.append(labels)

AxisError: axis 1 is out of bounds for array of dimension 1

In [4]:
features

[array([[193., 107., 293., ...,   4.,   2.,   0.],
        [191., 106., 294., ...,   4.,   2.,   2.],
        [191., 106., 293., ...,   4.,   2.,   0.],
        ...,
        [ 88., 113., 128., ..., 194.,   6.,   3.],
        [ 86., 113., 129., ..., 194.,   5.,   2.],
        [ 88., 112., 127., ..., 192.,   5.,   2.]]),
 array([[  8.,   8.,   8., ...,  25.,   7.,   2.],
        [  8.,   7.,   8., ...,  28.,   6.,   3.],
        [  8.,   8.,   8., ...,  28.,   6.,   0.],
        ...,
        [283., 292., 326., ...,   2.,   0.,   0.],
        [282., 292., 324., ...,   2.,   0.,   0.],
        [282., 291., 324., ...,   0.,   0.,   0.]]),
 array([[  4.,   4.,  12., ..., 162.,  45.,  24.],
        [  4.,   4.,  12., ..., 162.,  46.,  23.],
        [  4.,   4.,  12., ..., 162.,  47.,  24.],
        ...,
        [  2.,   6.,   8., ...,  10.,   5.,   6.],
        [  2.,   6.,   9., ...,  10.,   5.,   5.],
        [  2.,   6.,   9., ...,   9.,   4.,   5.]])]

In [5]:
import torch
data_list = features
alldata = []
for array in data_list:
    tensor = torch.from_numpy(array)

    alldata.append(tensor)

In [6]:
alldata

[tensor([[193., 107., 293.,  ...,   4.,   2.,   0.],
         [191., 106., 294.,  ...,   4.,   2.,   2.],
         [191., 106., 293.,  ...,   4.,   2.,   0.],
         ...,
         [ 88., 113., 128.,  ..., 194.,   6.,   3.],
         [ 86., 113., 129.,  ..., 194.,   5.,   2.],
         [ 88., 112., 127.,  ..., 192.,   5.,   2.]], dtype=torch.float64),
 tensor([[  8.,   8.,   8.,  ...,  25.,   7.,   2.],
         [  8.,   7.,   8.,  ...,  28.,   6.,   3.],
         [  8.,   8.,   8.,  ...,  28.,   6.,   0.],
         ...,
         [283., 292., 326.,  ...,   2.,   0.,   0.],
         [282., 292., 324.,  ...,   2.,   0.,   0.],
         [282., 291., 324.,  ...,   0.,   0.,   0.]], dtype=torch.float64),
 tensor([[  4.,   4.,  12.,  ..., 162.,  45.,  24.],
         [  4.,   4.,  12.,  ..., 162.,  46.,  23.],
         [  4.,   4.,  12.,  ..., 162.,  47.,  24.],
         ...,
         [  2.,   6.,   8.,  ...,  10.,   5.,   6.],
         [  2.,   6.,   9.,  ...,  10.,   5.,   5.],
         [ 

In [16]:
import numpy as np
features31=np.load('Data/resnet50-all--modern_office31.npy', allow_pickle=True)

labels31 = np.load('Data/labels-resnet50-all--modern_office31.npy', allow_pickle=True)


In [17]:
print(len(features31[0]))

496


In [20]:
len(labels31)

4104

In [19]:
data_list = features31.tolist()
alldata = []
for array in data_list:
    tensor = torch.from_numpy(array)

    alldata.append(tensor)
for i in range(len(alldata)):
    print(len(alldata[i]))
alllabels = [labels31[len(alldata[1]):3608], labels31[:len(alldata[0])]]
ylabels1 = []

    # Convert each one-hot encoded array to labels and append them to the list
for array in alllabels:
    labelss = np.argmax(array, axis=1)
    ylabels1.append(labelss)
alllabels = ylabels1

496
793
2815


In [11]:
alllabels

[array([15, 15, 15, ...,  4,  4,  4]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
        12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
        16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 1

In [2]:
import numpy as np

labels = np.load('Data/labels-resnet50-all--modern_office31.npy')

In [4]:
labels.shape

(4104, 31)

In [10]:
import pickle 

with open('Results/labels_dic.pkl', 'rb') as f:
    lab = pickle.load(f)

In [20]:
labels.shape

(4104, 31)

In [12]:
labels

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
import torch
features = np.load('Data/resnet50-all--modern_office31.npy', allow_pickle=True)

data_list = features.tolist()
alldata = []
for array in data_list:
    tensor = torch.from_numpy(array)
    alldata.append(tensor)
print(len(alldata))
labels = np.load('Data/labels-resnet50-all--modern_office31.npy', allow_pickle=True)


alllabels = [labels[len(alldata[1]):3608], labels[:len(alldata[0])],
                 labels[len(alldata[0]):(len(alldata[0]) + 793)]]
ylabels1 = []

    # Convert each one-hot encoded array to labels and append them to the list
for array in alllabels:
    labels = np.argmax(array, axis=1)
    ylabels1.append(labels)
alllabels = ylabels1
alllabels

3


[array([15, 15, 15, ...,  4,  4,  4]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
        12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
        16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 1

In [31]:
import os
import json
import random 

def extract_pressure_matrices(json_data):
    pressure_matrices = []
    for entry in json_data['pressureData']:
        pressure_matrix = entry["pressureMatrix"]
        pressure_matrices.append({"pressureMatrix": pressure_matrix})
    return pressure_matrices

def extract_features_from_pressure_matrices(pressure_matrices):
    
    flattened_data = [np.array(item["pressureMatrix"]).reshape(1,-1) for item in pressure_matrices]
    #print(flattened_data[0].shape)
    return np.concatenate(flattened_data, axis=0)
dic = {}
lab = {}

# Loop through subjects
for i in range(6, 9):
    
    folder_path = f'data/Subject_{i}/Posture_data'

    # Get all files in the folder
    files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
    
    l = []  # List to store feature arrays
     # List to store labels
    labels_list = []
    for f in files:
        x = int(f.split('.')[0][-1])  # Extract label from filename
        file_path = os.path.join(folder_path, f)
        
        # Check if the file is a JSON file
        if file_path.endswith('.json'):
            with open(file_path, 'r') as file:
                try:
                    data = json.load(file) 
                    pressure_matrices = extract_pressure_matrices(data)
                    features = extract_features_from_pressure_matrices(pressure_matrices)
                    l.append(features)
                    
                    # Create label array with 1 at index x
                    label_array = np.zeros((features.shape[0], 7))
                    label_array[:, x-1] = 1
                    labels_list.append(label_array)
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON in file {file_path}: {e}")
        else:
            print(f"Skipping non-JSON file: {file_path}")
    num = list(range(7))
    random.shuffle(num)
    
    dic[i] = np.concatenate([l[j] for j in num], axis=0)
    print(dic[i].shape)
    lab[i] = np.concatenate(labels_list,axis = 0)


(349, 256)
(236, 256)
(160, 256)


In [34]:
[i.shape for i in list(dic.values())]

[(349, 256), (236, 256), (160, 256)]

In [37]:
with open ('Results/labels_dic.pkl','rb') as file:
        lab = pickle.load(file) 
labels = list(lab.values())

In [38]:
labels

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]])]